### PR TITLE
do not inherit from ImageMapType

### PR DESCRIPTION
**Pull request by calvinmetcalf**
check it out @knownasilya it was a pretty strait forward fix, almost all of this was just cleaning up the code

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
you should be able to test with a `npm run build && npm link` in this repo and a `npm link maplarge-google && npm [rebuild however]` in the main repo

**Comment by knownasilya** [comment]
Testing now

**Comment by knownasilya** [comment]
ops, hate that button there..

**Comment by knownasilya** [comment]
Fix confirmed on repro code, testing on actual repo.

**Comment by knownasilya** [comment]
Also confirmed.

**Pull request merged**
